apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../
  - mailhog.yaml

# Reemplaza REGISTRY/puj/<svc>:latest por puj/<svc>:local (imagen construida en minikube)
images:
  - name: REGISTRY/puj/user-service
    newName: puj/user-service
    newTag: local
  - name: REGISTRY/puj/course-service
    newName: puj/course-service
    newTag: local
  - name: REGISTRY/puj/assessment-service
    newName: puj/assessment-service
    newTag: local
  - name: REGISTRY/puj/collaboration-service
    newName: puj/collaboration-service
    newTag: local
  - name: REGISTRY/puj/analytics-service
    newName: puj/analytics-service
    newTag: local
  - name: REGISTRY/puj/email-service
    newName: puj/email-service
    newTag: local
  - name: REGISTRY/puj/web-ui
    newName: puj/web-ui
    newTag: local

patches:
  - path: patch-storageclass.yaml
  - path: patch-pull-policy.yaml
  - path: patch-ingress.yaml
  - path: patch-email-smtp.yaml
