# TEMPLATE — valores reales deben provenir de AWS Secrets Manager / kubectl create secret
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: puj-platform
type: Opaque
stringData:
  DB_USER:            "puj_admin"
  DB_PASSWORD:        "CHANGE_ME"
  REDIS_PASSWORD:     "CHANGE_ME"
  RABBITMQ_USER:      "puj_rabbit"
  RABBITMQ_PASSWORD:  "CHANGE_ME"
  JWT_PRIVATE_KEY:    "CHANGE_ME_BASE64_PEM"
  JWT_PUBLIC_KEY:     "CHANGE_ME_BASE64_PEM"
  AWS_ACCESS_KEY_ID:     "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  SMTP_HOST:             "smtp.puj.edu.co"
  SMTP_PORT:             "587"
  SMTP_USER:             "CHANGE_ME"
  SMTP_PASSWORD:         "CHANGE_ME"
